name: Scheduled python
on:
  schedule:
  - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1.2.0
      - name: Run python
        run: |
          ls
          pwd
      - name: Trigger our build webhook on Netlify
        run: curl -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
